
files = [
         'mathieu.lornac.cv.lv',
         'mathieu.lornac.resume'
        ]

def compile_latex_file(f)
  system "pdflatex #{f}.tex"
end

desc "Compile the documents: #{files.join(' | ')}"
task :default do |t|
  files.each do |f|
    compile_latex_file(f)
  end
end

desc "Remove temporary files"
task :clean do |t|
  ['out', 'log', 'aux'].each do |e|
    files.each do |f|
      rm_f "#{f}.#{e}"
    end
  end
end

desc "Compilation loop"
task :auto do |t|
  lms = []
  files.each do |f|
    lms << Time.local(2000)
  end
  while 1 do
    files.each_with_index do |f, i|
      f = f + ".tex"
      if File.mtime(f) > lms[i]
        Rake::Task["default"].execute
        lms[i] = File.mtime f
      end
    end
    sleep 1
  end
end
